## select roles to install
anki_install: true
discord_install: true
docker_install: true
dotfiles_install: true
fonts_install: true
fzf_install: true
gimp_install: true
git_install: true
i3_install: true
jetbrains_install: true
mpd_install: true
network_manager_install: true
ubuntu_setup_install: true
packer_install: true
polybar_install: true
qemu_install: true
ranger_install: true
rtl88_install: true
syncthing_install: true
urxvt_install: true
vagrant_install: true
vim_install: true
virtualbox_install: true
vscode_install: true
xdg_install: true
ytdlp_install: true
zathura_install: true
zotero_install: true
zsh_install: true

# --- Ubuntu setup ---
ubuntu_user: ""
ubuntu_releases: ""
apt_packages:
  # ---- Base Utils ----
  - keepassxc
  - thunar
  - sxiv
  - mupdf
  - borgbackup
  - firefox
  - thunderbird
  - okular # PDF reader w/ annotations
  - pcmanfm
  - bat
  - cantata # GUI frontend for mpd
  - dex
  - vim
  - ffmpeg
  - highlight
  - libreoffice
  - libreoffice-style-sifr
  - xarchiver
  - piper # gui for mouse config
  - xwallpaper
  - lxappearance
  - qt5-style-plugins
  #- qt4-qtconfic
# ---- Window Manager ----
  - arandr
  - autorandr
  - blueman #bluetooth GUI
  - redshift
  - redshift-gtk
# ---- Video ----
  - mpv
  - vlc
  - x264
  - x265
# ---- Audio ----
  #- pavucontrol #GUI for pulseaudio volume control
  - alsa-utils
  - pulseaudio
  - pulseaudio-module-bluetooth
  - pulseaudio-utils
# ---- Network clients ----
  - openssh-client
# ---- Development ----
  # - texlive-full
  - qpdf
  - pandoc
  - mariadb-server
  - binutils
  - dos2unix
  - jq

apt_removals: []
ppas: []
no_ppa_packages: []
default_user: ""
default_group: ""
default_files: []

# --- Docker ---
docker_users: #[]
  - "{{ ansible_user_id }}"
docker_apt_release_channel: stable
docker_install_compose: true
docker_compose_version: "v2.4.1"

# --- Dotfiles ---
dotfile_repo: ""

# --- Fonts ---
fonts_user: "{{ ansible_user_id }}"
fonts_repository: []
nerdfonts_single_fonts: []

# --- FZF ---
# add sourcing ~/.fzf.bash to your normal shell config?
fzf_update_rc: true
# enable/Disable fuzzy completion (bash & zsh)?
fzf_completion: true
# enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)?
fzf_key_bindings: false
# runs fzf configuration script when set to false, otherwise will use custom config paths for bash and zsh if fzf_bash or fzf_zsh true
fzf_template: false
# put fzf bash config in custom path
fzf_bash: false
# put fzf zsh config in custom path
fzf_zsh: false

# --- Git ---
git_user: "{{ ansible_user_id }}"  # or 'system'

gitconfig_set: true
gitignore_set: true
gitconfig_set_commit_message: true

gitconfig_alias:

gitconfig_color:

gitconfig_core:
  editor: vim

gitconfig_diff:

gitconfig_user:

gitconfig_commit:

gitconfig_other:

gitignore: []

# --- i3 ---
i3: false # install i3 from default repository
i3_gaps_ppa: true # add regolith ppa to install i3-gaps
i3_gaps_manual: false # install i3-gaps by building it from source
i3_extras: true # install i3 extra packages defined in i3_extras_packages variable

i3_extras_packages:
  - picom
  - dunst
  - rofi

# --- Jetbrains Development Tools ---
intellij: false # boolean for installing intellij
intellij_code: IC 

pycharm: false # boolean for installing pycharm
pycharm_code: PCC

# --- mpd ---
mpd_sample_config: false # use mpd sample config

mpc_install: true # boolean for installing mpc

ncmpcpp_sample_config: false  # use ncmpcpp sample config
ncmpcpp_install: true # boolean for installing ncmpcpp

# --- Network_manager ---
network_manager_nm_applet: true
network_manager_plugin_openvpn: true
network_manager_plugin_l2tp: false
network_manager_plugin_openconnect: false
network_manager_plugin_pptp: false
network_manager_plugin_ssh: true
network_manager_plugin_strongswan: false
network_manager_plugin_vpnc: true

# --- Ranger ---
ranger_plugins: #[]
  - repository: https://github.com/alexanderjeurissen/ranger_devicons.git
    directory: devicons

ranger_python2_packages: []
ranger_python3_packages: []

# --- rtl88_themes ---
rtl_themes:
  - directory: rtl88-arc_darkest_complete
    version: Arc-Darkest-COLORS-Complete-Desktop

# --- urxvt ---
urxvt_extensions: #[]
  - https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size # https://github.com/majutsushi/urxvt-font-size

# --- vim ---
vim_installed_packages: #[]
  - vim
vim_removed_packages:
  - vim-tiny
  - vim-nox
vim_installed_plugins_start: #[]
  - repo: "https://github.com/vim-airline/vim-airline"
  - repo: "https://github.com/Raimondi/delimitMate.git"
  - repo: "https://github.com/godlygeek/tabular.git"
  - repo: "https://github.com/tpope/vim-commentary.git"
  - repo: "https://github.com/tpope/vim-fugitive.git"
  - repo: "https://github.com/tpope/vim-repeat.git"
  - repo: "https://github.com/tpope/vim-surround.git"
  - repo: "https://github.com/vim-syntastic/syntastic.git"
  - repo: "https://github.com/Vimjas/vim-python-pep8-indent.git"
  - repo: "https://github.com/junegunn/goyo.vim.git"
  - repo: "https://github.com/lervag/vimtex.git"
vim_installed_plugins_opt: []
vim_removed_plugins_start:
  []
vim_removed_plugins_opt:
  []

# --- Visual Studio Code ---
vscode_extensions_install: #[]
  - alefragnani.Bookmarks
  - alefragnani.project-manager
  - ban.spellright
  - bertieblackman.snappier
  - bierner.color-info
  - CoenraadS.bracket-pair-colorizer-2
  - DavidAnson.vscode-markdownlint
  - dbaeumer.vscode-eslint
  - donjayamanne.githistory
  - dsznajder.es7-react-js-snippets
  - eamodio.gitlens
  - ecmel.vscode-html-css
  - eriklynd.json-tools
  - esbenp.prettier-vscode
  - formulahendry.auto-close-tag
  - goessner.mdmath
  - humao.rest-client
  - IBM.output-colorizer
  - idleberg.icon-fonts
  - James-Yu.latex-workshop
  - jebbs.plantuml
  - jprestidge.theme-material-theme
  - jsaulou.theme-by-language
  - kisstkondoros.vscode-gutter-preview
  - marcostazi.VS-code-vagrantfile
  - mechatroner.rainbow-csv
  - mikestead.dotenv
  - mrmlnc.vscode-apache
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-toolsai.jupyter
  - ms-vscode-remote.remote-containers
  - naumovs.color-highlight
  - Nimda.deepdark-material
  - oderwat.indent-rainbow
  - redhat.vscode-yaml
  - ritwickdey.live-sass
  - ritwickdey.LiveServer
  - rogalmic.bash-debug
  - samuelcolvin.jinjahtml
  - Shan.code-settings-sync
  - shd101wyy.markdown-preview-enhanced
  - steoates.autoimport
  - streetsidesoftware.code-spell-checker
  - teabyii.ayu
  - vangware.dark-plus-material
  - vincaslt.highlight-matching-tag
  - vscode-icons-team.vscode-icons
  - vscodevim.vim
  - WakaTime.vscode-wakatime
  - wayou.vscode-todo-highlight
  - yzhang.markdown-all-in-one
  - Zignd.html-css-class-completion
vscode_extensions_uninstall: []

# --- Xorg ---
### Set your preferred default applications (MIME-Types)
xdg_mime_defaults:
  - desktop_file: sxiv.desktop
    mime_types:
      - image/jpg
      - image/jpeg
      - image/pjpeg
      - image/png
      - image/tiff
      - image/webp
      - image/bmp
      - image/gif
  - desktop_file: mpv.desktop
    mime_types:
      - video/x-matroska
      - video/mp4
      - video/H264
      - video/mpeg
      - video/webm
      - video/ogg
      - video/avi
  - desktop_file: zathura.desktop
    mime_types:
      - application/pdf
      - application/postscript
      - application/eps
      - application/x-eps
  - desktop_file: firefox.desktop
    mime_types:
      - text/html
      - application/xhtml_xml
      - application/x-mimearchive
      - x-scheme-handler/http
      - x-scheme-handler/https
      - x-scheme-handler/ftp
      - x-scheme-handler/chrome
  - desktop_file: vim.desktop
    mime_types:
      - text/xml
      - text/plain
  - desktop_file: anki.desktop
    mime_types:
      - application/x-colpkg
      - application/x-apkg
      - application/x-ankiaddon
  - desktop_file: thunderbird.desktop
    mime_types:
      - x-scheme-handler/mailto
      - application/x-xpinstall
  - desktop_file: pcmanfm.desktop
    mime_types:
      - inode/directory
  - desktop_file: ncmpcpp.desktop
    mime_types:
      - audio/mpeg
      - audio/ogg
      - audio/opus
      - audio/webm
      - audio/wav
      - audio/mpeg3

# --- yt-dlp ---
ytdlp_update: true

# --- ZSH ---
zsh_user: []
zsh_plugins_git: #[]
    - name: zsh-syntax-highlighting
      zsh_file: zsh-syntax-highlighting.zsh
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    - name: zsh-autosuggestions
      zsh_file: zsh-autosuggestions.zsh
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
    - name: powerlevel10k
      zsh_file: powerlevel10k.zsh-theme
      repo: https://github.com/romkatv/powerlevel10k.git
zsh_plugins_package_manager: #[]
  - powerline
omz_install: false
omz_configure: false
